# The color_scheme to use for the app.
# See: https://docs.iced.rs/iced/enum.Theme.html for full list of options
# (no Custom support)
color_scheme = "CatppuccinMocha"

# If the background of the app should be set to be transparent
# This can be removed once custom colour schemes are supported
transparent_background = false

app_prefixes = { 
    AppSearch  = "" ,
    WebSearch  = "!",
    FileSearch = "'",
    HelpScreen = "?",
    Calculator = "=" 
}

# The background text where you type your search
input_prompt = "Type to search"

# Show icons for search results
show_icons = true

[file_settings]
search_directories = ["Documents", "Desktop", "Downloads"]
