
[window]
opacity = 0.70
blur = true
padding = {x = 2, y = 2}
dynamic_padding = true

[cursor]
style = { shape = "Beam" }

[font]
# normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
normal = { family = "ComicMono Nerd Font", style = "Regular" }
size = 14

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
